### ISSUE TITLE
Exdir not found

### ISSUE THREAD

**Issue by rjthomas33** [jbryer/ipeds#5]
When trying to download a specific year of ipeds data I get the following error:

Final data not available for 2017-18
Zip file already downloaded. Set force=TRUE to redownload.
Error in unzip(dest, exdir = dir) : 'exdir' does not exist
In addition: Warning message:
In download_ipeds(year = 2018) :
  Downloading the provisional database for 2017-18.

The .zip file gets downloaded correctly, but it is unable to unzip. When I manually unzip the file in the same folder, I am still unable to load the data using ipeds::load_ipeds(2018) as it says the file is not found

**Comment by jbryer** [comment]
I presume this is on Windows. There is a known bug on windows that will
hopefully be fixed before September.

**Comment by rjthomas33** [comment]
Yes, it is windows. Thanks for the reply

**Comment by tyleransom** [comment]
Just adding here that I too am having this issue on Windows 10.

**Comment by tyleransom** [comment]
@jbryer Thanks for checking on this. I am still getting this error when I run [`ipeds2.R`](https://github.com/jbryer/ipeds/blob/83f911c075eed070d9659f4ef11b1205bb35fb79/demo/ipeds2.R).

```r
> # Download data
> ipeds::download_ipeds(year = 2017)
trying URL 'https://nces.ed.gov/ipeds/tablefiles/zipfiles/IPEDS_2016-17_Final.zip'
Content type 'application/x-zip-compressed' length 67407371 bytes (64.3 MB)
downloaded 64.3 MB

Error in unzip(dest, exdir = dir) : 'exdir' does not exist
```

I will play around with things and submit a PR if I figure something out.

**Comment by jbryer** [comment]
Did you load the ipeds package before calling this command? That is, did
you call library(ipeds). What does `getOption('ipeds.download.dir')`
return? The value of this option is not set until the package is loaded.

**Comment by jbryer** [comment]
I pushed an update to Github that should allow this to work without loading the package.

**Comment by tyleransom** [comment]
I'm fairly certain I loaded the package first (otherwise I feel like `ipeds::download_ipeds(year = 2017)` would have failed) but I'll give it a try and let you know if there's still a problem.

**Comment by tyleransom** [comment]
I'm still getting the same error, even after updating the package this morning. So I'm not sure what's going on, but I will investigate.

**Comment by jbryer** [comment]
Just an FYI, when calling functions using the package::function() do not
necessarily load the package (i.e. call the .onLoad function). Notice here:

```
> ipeds::available_ipeds()
> search()
 [1] ".GlobalEnv"        "tools:rstudio"     "package:stats"
"package:graphics"  "package:grDevices"
 [6] "package:utils"     "package:datasets"  "package:methods"
"Autoloads"         "package:base"
```

The `ipeds` package is not listed as a loaded package.
